# Generated by Django 4.1.7 on 2023-03-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_task_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('New', 'Новый'), ('In progress', 'В процессе'), ('Done', 'Выполнено')], default='New', max_length=20, verbose_name='Наименование статуса'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(choices=[('Task', 'Задача'), ('Bug', 'Ошибка'), ('Enhancement', 'Улучшение')], default='Task', max_length=20, verbose_name='Наименование типа'),
        ),
    ]
